### ISSUE TITLE
python3 conversion error

### ISSUE THREAD

**Issue by panizza** [the-lazy-fox/script.tvtime#14]
Hi, I just upgraded to the lastest version, but there still are some issues related to the python3 conversion. For example when you mark an episode as watched the following error appears
```
2021-03-19 11:38:20.824 T:10612   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
          - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
         Error Type: <class 'TypeError'>
         Error Contents: '>' not supported between instances of 'str' and 'int'
         Traceback (most recent call last):
           File "C:\Users\Andrea\AppData\Roaming\Kodi\addons\script.tvtime\default.py", line 209, in onNotification
             if len(item['showtitle']) > 0 and item['season'] > 0 and item['episode'] > 0 and item['episode_id'] > 0:
         TypeError: '>' not supported between instances of 'str' and 'int'
         -->End of Python script error report<--
```
I guess this depends on how the episode_id is stored inside kodi, so this is an easy fix.
But after I fixed that, another one appears
```
2021-03-19 11:53:11.821 T:16564   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
          - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
         Error Type: <class 'AttributeError'>
         Error Contents: 'bytes' object has no attribute 'encode'
         Traceback (most recent call last):
           File "C:\Users\Andrea\AppData\Roaming\Kodi\addons\script.tvtime\default.py", line 210, in onNotification
             self.filename = '%s.S%.2dE%.2d' % (formatName(item['showtitle']), float(item['season']), float(item['episode']))
           File "C:\Users\Andrea\AppData\Roaming\Kodi\addons\script.tvtime\default.py", line 351, in formatName
             return normalizeString(filename)
           File "C:\Users\Andrea\AppData\Roaming\Kodi\addons\script.tvtime\default.py", line 369, in normalizeString
             return unicodedata.normalize('NFKD', str).encode('ascii','ignore').encode('UTF-8','replace')
         AttributeError: 'bytes' object has no attribute 'encode'
         -->End of Python script error report<--
```

I know this is a python3 conversion issue, because they changed how strings are represented in python3 as explained [here](https://portingguide.readthedocs.io/en/latest/strings.html)
but I need someone to confirm this issue is reproducible and it's not just a problem on my end. @jupiler5 @the-lazy-fox can one of you two confirm that?

Then I'll look into it and create a pull request

**Comment by batkins2** [comment]
I also ran into these issues. To fix the 2nd issue, I just changed the last encode to decode. Seems to be working after that.

**Comment by panizza** [comment]
> I also ran into these issues. To fix the 2nd issue, I just changed the last encode to decode. Seems to be working after that.

Yes, I've done the same thing and I also fixed the first error. I'm already creating a pull request

**Comment by the-lazy-fox** [comment]
Great news.
Thanks for the PR 👍🏼

**Comment by GofranAy** [comment]
For this we need to wait for the next version update ? Or do i need to change some lines in kody users location

**Comment by panizza** [comment]
> For this we need to wait for the next version update ? Or do i need to change some lines in kody users location

I just created the [pull request](https://github.com/the-lazy-fox/script.tvtime/pull/16). Just wait for the release by @the-lazy-fox

**Comment by the-lazy-fox** [comment]
Thanks @panizza 
Here is the release: https://github.com/the-lazy-fox/script.tvtime/releases/tag/v2.0.1
