### ISSUE TITLE
Zero devision exception

### ISSUE THREAD

**Issue by SamJongenelen** [the-lazy-fox/script.tvtime#4]
Using streaming videos on Kodi (Seren). 
Any ideas?

Error Type: <type 'exceptions.ZeroDivisionError
Error Contents: float division by zero
Traceback (most recent call last):
File /storage/emulated/0/Android/data/org.xbmc.kodi/files/kodi/addons
actual_percent =(self._last_pos/self._total_time) * 100
Zero DivisionError: float division by zero

**Comment by the-lazy-fox** [comment]
Hello @SamJongenelen,
This error is coming from
`actual_percent = (self._last_pos/self._total_time)*100` because the result of `self._total_time = player.getTotalTime()` is 0 in your case.
From what I know, this addon is only working for the physical library files.
I can't help further.

**Comment by SamJongenelen** [comment]
hey @alxlaxv  - I indeed noticed that there was no support for streaming. However, can this be built in?

**Comment by the-lazy-fox** [comment]
Hello,
Even if we can go through the player timing gate, we will face the lack of TVDBiD as the assets are not stored and enriched in the Kodi library.
Regards

**Comment by SamJongenelen** [comment]
OK, I understand it's a challenge. I am sure it can be made to work (as the Trakt.TV addons are able to do it). 
Easier said then done of course...
