### ISSUE TITLE
login error 33804

### ISSUE THREAD

**Issue by deflep7702** [the-lazy-fox/script.tvtime#5]
Yesterday I was logged out and upon trying to login, I keep getting that error code. Any ideas?

**Comment by panizza** [comment]
Same error here. And the log files are pretty useless.

**Comment by the-lazy-fox** [comment]
Hello @deflep7702 and @panizza,
This error is related to an issue during the cleint authorization process. I will have to dig into the code to check that as it's new to me.
Do you have a working internet access on your device? Can you try to reach this url: https://api.tvtime.com/v1/oauth/device/code

**Comment by panizza** [comment]
Yes, i can access the URL you provided. I tried the official plugin (the one available in the official repo) and it appears to be working.

**Comment by deflep7702** [comment]
It appears to be working again, thanks for all the work you have done on this add-on by the way!

**Comment by obygyv** [comment]
I have the error 33804 with the addon in the official repo, which version do you use?

**Comment by obygyv** [comment]
Trying to reach https://api.tvtime.com/v1/oauth/device/code give me the following result:

code | 404
-- | --
result | "KO"
message | null

I still have the error 33804. Any advice?

**Comment by Ross1181** [comment]
It worked fine until 2 days ago, now I have error 33804 too on all my devices (pc windows, Mac and nvidia shield tv). What happens?

**Comment by deflep7702** [comment]
Yeah I've had the same happen, not really sure, maybe an issue with the TvTime API?
________________________________

**Comment by GofranAy** [comment]
Tvtime is having some issue i think that is why check twitter

**Comment by Arryby** [comment]
starting to encounter again the login error 33804 on Kodi Leia 18.9

**Comment by drag0nst0ne** [comment]
biggest necro of github. but yeah, its happening to me too

**Comment by jupiler5** [comment]
Same problem.
I tried to reach https://api.tvtime.com through web browser, unreachable.
I think there's an issue with the TVTime api...

**Comment by nonobio** [comment]
Hello,

Same error for me with TV Time 1.2.4 and Kodi 18.9 on Windows 7.

Thanks

**Comment by Nwalma** [comment]
Hello

same error as well with tv time 1.2.4 and kodi 18.9
any updates?

**Comment by jupiler5** [comment]
Not yet.
As the issue comes from TV Time api (unreachable), the problem will occur on any version of Kodi.
I sent an e-mail to TV Time this week-end to have news about their API. I'm still waiting for an answer.

As soon as I have one, I come back to you.

**Comment by jupiler5** [comment]
To understand the problem, the Kodi TV Time plugin communicates with TV Time through TV Time public api (Root URL: https://api.tvtime.com).
On login, the plugin tries to reach https://api.tvtime.com/v1/oauth/device/code, that doesn't answer anymore (plugin returns **33804** error code if not succeeded).
Even the documentation (https://api.tvtime.com/doc) is no more available...

**Comment by the-lazy-fox** [comment]
Hi all,
My investigation led to the same point as @jupiler5.
Please let use know if they answer to you!
Thanks!

**Comment by jupiler5** [comment]
I got an answer from TV Time support today:
"
Tanzy (TV Time)

Feb 19, 2021, 11:10 PST
Hi Jupiler5,

We've been made aware that our public API is not working as expected. This may cause issues with your calendar, 3rd party app syncing, as well as using TV Time Google Chrome extension.

We've escalated this issue to our dev team for further investigation. We'll let you know as soon as we have an update on the issue.

We're sorry for the inconvenience, but we'll get back to you as soon as we have an update.

Best,

Tanzy
Head of Support, TV Time_
"
At least it's not intentional and it should work again shortly.

**Comment by nonobio** [comment]
Hi,

I had the same reply from support.

**Comment by panizza** [comment]
Try this https://github.com/the-lazy-fox/script.tvtime/pull/12
We fixed the login issue and other problems

**Comment by jupiler5** [comment]
That works !!! Thanks a lot panizza for your work ! :-)
New working plugin: https://github.com/RSantos94/script.tvtime

**Comment by nonobio** [comment]
Thanks a lot.

I have not updated my Kodi yet, i'm on 18.9.  I tried to install the new plugin but i had an error about xbmc python version 3.0.0 not installed.

Is it possible to fix the issue for the add-on working on Kodi 18 ?

**Comment by deflep7702** [comment]
The last plug-in before this one still works, TvTime fixed the API issue.
________________________________

**Comment by nonobio** [comment]
Oups, yes it works; i just had to reconnect it ;) . Thanks

**Comment by the-lazy-fox** [comment]
New release published with your fixes.
Thanks a lot guys.

**Comment by jupiler5** [comment]
https://api.tvtime.com/ is offline... again...

So if you have some problems at the moment, it's not a script problem but the TVTime public api website that's down...

**Comment by enrique131** [comment]
https://api.tvtime.com/ seems to be down again. I cannot log in. Error 33804 is back for me

**Comment by Nwalma** [comment]
I can't log in either for quite a few days now

**Comment by enrique131** [comment]
> I can't log in either for quite a few days now

As far as i know unless access to here: https://api.tvtime.com/ is possible you wont be able to access.
I emailed tv time and they confirmed that they know about the API and they are working on it... so we can only wait for it to be fixed

**Comment by Nwalma** [comment]
Is it still not working?

**Comment by obygyv** [comment]
> 
> 
> Is it still not working?

TVtime staff announced the end of the API. So the plugin won't work again. Some smart people may find an alternative solution, but for now, I think we are screwed...

**Comment by the-lazy-fox** [comment]
What a pitty news...
If someone has any idea, feel free :)

**Comment by lluberti** [comment]
I have migrated to the following solution:

trakt to store the playbacks
https://kodi.wiki/view/Add-on:Trakt

and the MovieBase app which automatically syncs with trakt
https://www.moviebase.app/

**Comment by enrique131** [comment]
> I have migrated to the following solution:
> 
> trakt to store the playbacks
> https://kodi.wiki/view/Add-on:Trakt
> 
> and the MovieBase app which automatically syncs with trakt
> https://www.moviebase.app/

I have https://trakt.tv/ as well. unfortunately the android app is really slow for me. It takes around 5 minutes to sync and it can get really annoying. I'm using SeriesGuide for it. If anyone knows a better one (better UI & sync speed) i will have a look

**Comment by GofranAy** [comment]
Maybe simkl.com is somthing for you i like it

**Comment by lluberti** [comment]
> > I have migrated to the following solution:
> > trakt to store the playbacks
> > https://kodi.wiki/view/Add-on:Trakt
> > and the MovieBase app which automatically syncs with trakt
> > https://www.moviebase.app/
> 
> I have https://trakt.tv/ as well. unfortunately the android app is really slow for me. It takes around 5 minutes to sync and it can get really annoying. I'm using SeriesGuide for it. If anyone knows a better one (better UI & sync speed) i will have a look

How long have you not used MovieBase?
lately it seems to me much improved.
synchronization takes a few seconds and in my catalog I have thousands of movies and TV series

**Comment by Ross1181** [comment]
> > I have migrated to the following solution:
> > trakt to store the playbacks
> > https://kodi.wiki/view/Add-on:Trakt
> > and the MovieBase app which automatically syncs with trakt
> > https://www.moviebase.app/
> 
> I have https://trakt.tv/ as well. unfortunately the android app is really slow for me. It takes around 5 minutes to sync and it can get really annoying. I'm using SeriesGuide for it. If anyone knows a better one (better UI & sync speed) i will have a look

On iPhone I use Watcht for Trakt or TV Show Tracker (I don’t know if they exist for Android). Only the first sync takes some time, after that it is much faster

**Comment by enrique131** [comment]
thanks for the suggestions. I am an android user. i sent an email to developer to see if there is something to be done for faster sync. I am a premium user and i really like to UI of the app. 
trakt.tv online is a great site. you can check when you watch an episode, or movie (date and time) If only the sync can be a bit faster.... lets hope the dev can help to tune it for me.
